on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push Backend Ruby
        uses: docker/build-push-action@v6
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-ruby:${{ env.IMAGE_TAG }}

      - name: Build and push Frontend React
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd client
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-react:${{ env.IMAGE_TAG }}

  # deployment:
  #   runs-on: ubuntu-latest
  #   needs: build-docker
  #   steps:
  #     - name: Deployment to idcloudhost server
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.SERVER_PRIVATE_KEY }}
  #         port: 22
  #         script: |
  #           docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-resume:nextjs_${{ github.sha }}
  #           docker stop my-resume
  #           docker rm my-resume
  #           docker run -d --name my-resume -p 9876:3000 ${{ secrets.DOCKERHUB_USERNAME }}/my-resume:nextjs_${{ github.sha }}
  #           docker image prune -a -f
  #           echo "Deployment successfully ✅"
